# Generated by Django 4.2 on 2023-08-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='difficulty',
            field=models.IntegerField(choices=[(20, 'Very Easy'), (15, 'Easy'), (10, 'Normal'), (5, 'Hard'), (3, 'Very Difficult'), (1, 'Extremely Difficult')], default=10),
        ),
    ]
