version: "3.9"
   
services:
  db:
    image: postgres:15
    # restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db.prod
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.backend.prod
    restart: always
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    volumes:
      - .:/code
      # - uploads:/backend/uploads
      - staticfiles:/backend/staticfiles
  nginx:
    image: arenchf/dock
    # build: 
    #   context: .
    #   dockerfile: ./webserver/Dockerfile
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - staticfiles:/staticfiles
      - ./webserver/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email arenchf@gmail.com -d vobolio.com --agree-tos
volumes:
  postgres_data:
  staticfiles:
  # uploads: