version: "3.9"
   
services:
  db:
    image: postgres:15
    # restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db.prod
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.backend.prod
    restart: always
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    volumes:
      - static:/backend/static
  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  postgres_data:
  static: