# Generated by Django 4.2 on 2023-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_trainingday_created_by_alter_trainingday_dictionary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='progress',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
